name: Deploy Muninn

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, gaia]
    env:
      DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
      OBSIDIAN_VAULT_PATH: ${{ vars.OBSIDIAN_VAULT_PATH }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Deploy Stack
        run: |
          ./scripts/deploy.sh "muninn" docker-compose.yml
